feat: If `core.autocrlf` is enabled, replace CRLF with LF when adding to index
gitpython-developers/GitPython pull request #1441
Opened 2022-05-17 18:38 UTC by rdbisme

This is to mimick the same behaviour the standard git command has.

2022-05-17 18:50 UTC, rdbisme commented
It would be much easier to contribute if using `black` for style autolinting

2022-05-17 23:41 UTC, Byron commented
May I ask to adjust the commits to not do code formatting? I am happy to run it through `black` to unify the style and if it doesn't make it (too much) worse, but that should be a separate step.

All these changes are like noise to the signal making a review harder than it has to be. Thanks.

2022-05-18 00:05 UTC, Byron requested changes
May I ask to adjust the commits to not do code formatting? I am happy to run it through black to unify the style and if it doesn't make it (too much) worse, but that should be a separate step.

All these changes are like noise to the signal making a review harder than it has to be. Thanks.

2022-05-18 11:08 UTC, rdbisme commented
Thanks for taking the time of applying black. I rebased everything on top of the latest commit and now the changes should more clear :)

2022-05-19 00:11 UTC, Byron commented
Thanks for the contribution and the intention to fix a shortcoming.
However, I don't feel comfortable to add 'a very special filter' that will inadvertently affect current users that build upon the existing, very limited behaviour. It has a huge potential to cause breakage and thus I see no way to add it in its current form.

GitPython has been done very much in that fashion - implement something to mimic the actual behaviour of git - which has caused an incredible amount of problems and surprises down the road. It's just not a paradigm that should be continued.

I am sorry, but I see no way forward for this PR, and thank you for your understanding.

2022-05-19 17:16 UTC, rdbisme commented
> Thanks for the contribution and the intention to fix a shortcoming. However, I don't feel comfortable to add 'a very special filter' that will inadvertently affect current users that build upon the existing, very limited behaviour. It has a huge potential to cause breakage and thus I see no way to add it in its current form.
> 
> GitPython has been done very much in that fashion - implement something to mimic the actual behaviour of git - which has caused an incredible amount of problems and surprises down the road. It's just not a paradigm that should be continued.
> 
> I am sorry, but I see no way forward for this PR, and thank you for your understanding.

Ok, no problem. Thanks for reviewing! :)

2022-05-19 17:16 UTC, closed without merging