Fix command injection
gitpython-developers/GitPython pull request #1518
Opened 2022-12-21 03:09 UTC by stsewd

Add `--` in some commands that receive user input
and if interpreted as options could lead to remote code execution (RCE).

There may be more commands that could benefit from `--` so the input is never interpreted as an option,
but most of those aren't dangerous.

Fixed commands:

- push
- pull
- fetch
- clone/clone_from and friends
- archive (not sure if this one can be exploited, but it doesn't hurt adding `--` :))

For anyone using GitPython and exposing any of the GitPython methods to users, make sure to always validate the input (like if starts with `--`). And for anyone allowing users to pass arbitrary options, be aware that some options may lead to RCE, like `--exc`, `--upload-pack`, `--receive-pack`, `--config` (https://github.com/gitpython-developers/GitPython/pull/1516).

Ref https://github.com/gitpython-developers/GitPython/issues/1517

2022-12-21 07:08 UTC, Byron requested changes
Thanks a million, much appreciated. Can we have at least one test along the lines of `Repo.clone(…touch pawn…)` that will be fixed by this PR? That way it's anchored in something that provably existed, and tests provide great context on why a change was made.

When merged, I will adjust the changelog right away to include a note about this and link back here, as it might be a breaking change for some despite this being part of a patch release.

2022-12-22 03:20 UTC, stsewd commented
I have added 2 tests (for clone and clone_from), wasn't able to write a test to exploit the other ones easily.

2022-12-22 16:08 UTC, merged

2022-12-22 16:11 UTC, Byron commented
Thanks a lot! The changelog was updated and I hope there can be a release soon once #1516 was merged. If you have some bandwidth, I'd really appreciate if you could take over that PR as I think it's very close to being merged but is idling unnecessarily.

2022-12-23 03:32 UTC, stsewd commented
I'll give it a try tomorrow 👍

2023-02-28 07:00 UTC, Testertime commented
> as it might be a breaking change for some despite this being part of a patch release.

And you were right Baron, seeing how the commit broke code for Stable Diffusion web UI as referenced above