Proposed change to get_values behavior
gitpython-developers/GitPython pull request #1535
Opened 2023-01-10 19:06 UTC by kfreezen

get_values() did not load existing sections before checking the `_sections` property.

**NOTE:** Haven't written a test to check for this yet.

2023-01-10 19:08 UTC, kfreezen commented
Proposed fix for #1534

2023-01-10 19:14 UTC, kfreezen commented
Looking at test here; I suppose we can leave it raising a KeyError. The main fix was force-loading the `_sections` attribute before checking the list.

I'll re-commit using KeyError.

2023-01-11 06:52 UTC, Byron requested changes
Thanks a lot, much appreciated!

I think the commit should link back to the issue it resolve to create a more declarative history.
Finally it should be possible to devise a test that would fail without this change to cement it. Otherwise it might be removed in future because it's unclear why eager loading of sections is necessary.

2023-02-16 05:23 UTC, Codym48 commented
@kfreezen, consider accepting https://github.com/kfreezen/GitPython/pull/1 to add test coverage for this change? I verified it fails on main:

![image](https://user-images.githubusercontent.com/34431661/219275914-e3c8e9df-4f26-4f3d-b89b-a5a511f7f56b.png)

2023-02-16 16:27 UTC, Byron commented
Closing as it's superseded by #1555

2023-02-16 16:27 UTC, closed without merging