fix files list on file rename
gitpython-developers/GitPython pull request #1537
Opened 2023-01-12 01:58 UTC by teknoraver

GitPython parses the output of `git diff` to get the files changed in a commit.
This breaks when a commit contains a file rename, because the output of `git diff` is different than expected.
This is the output of a normal commit:
```diff
$ git diff 6ab9810cfe6c^ 6ab9810cfe6c
diff --git a/drivers/clk/zynqmp/divider.c b/drivers/clk/zynqmp/divider.c
index 05788d8325d4..33a3b2a22659 100644
--- a/drivers/clk/zynqmp/divider.c
+++ b/drivers/clk/zynqmp/divider.c
```
And this a commit containing a rename:
```diff
$ git diff db401875f438^ db401875f438
diff --git a/tools/testing/selftests/drivers/net/mlxsw/spectrum-2/devlink_trap_tunnel_ipip6.sh b/tools/testing/selftests/drivers/net/mlxsw/devlink_trap_tunnel_ipip6.sh
similarity index 99%
rename from tools/testing/selftests/drivers/net/mlxsw/spectrum-2/devlink_trap_tunnel_ipip6.sh
rename to tools/testing/selftests/drivers/net/mlxsw/devlink_trap_tunnel_ipip6.sh
index f62ce479c266..878125041fc3 100755
--- a/tools/testing/selftests/drivers/net/mlxsw/spectrum-2/devlink_trap_tunnel_ipip6.sh
+++ b/tools/testing/selftests/drivers/net/mlxsw/devlink_trap_tunnel_ipip6.sh
```
This can be triggered by this code:
```python
for commit in repo.iter_commits():
    print(commit.hexsha)
        for file in commit.stats.files:
            print(file)
```
Which will print for the normal commit:
```
6ab9810cfe6c8f3d8b8750c827d7870abd3751b9
'drivers/clk/zynqmp/divider.c'
```
And when there is a rename:
```
db401875f438168c5804b295b93a28c7730bb57a
('tools/testing/selftests/drivers/net/mlxsw/{spectrum-2 => '
'}/devlink_trap_tunnel_ipip6.sh')
```
Fix this by pasing the --no-renames option to `git diff` which ignores renames and print the same output as if the file was deleted from the old path and created in the new one.

2023-01-12 06:32 UTC, Byron requested changes
Thanks a lot!

It should be straightforward to add a test that motivates this changes. The test-suite uses fixture files which could be derived from an example repository.

With a test that fails without this change, the fix can be merged.

Thank you

2023-01-12 14:18 UTC, teknoraver commented
@Byron done, and I rewrote the commit message using GitPython hashes, so is simpler for anyone to test

2023-01-13 07:25 UTC, Byron requested changes
Thanks a lot, this looks like the way to go!

Instead of checking what it shouldn't be (which is a huge set of possible values), could you instead check what it should be? How does a rename look like with the current interface, I'd be very interested to see that.

For posterity, here is what `git` thinks about this:

```patch
commit 185d847ec7647fd2642a82d9205fb3d07ea71715
Author: Dominic <<redacted>@gmail.com>
Date:   Mon Jul 12 17:02:21 2021 +0100

    Update and rename test_pytest.yml to Future.yml

diff --git a/.github/workflows/test_pytest.yml b/.github/workflows/Future.yml
similarity index 92%
rename from .github/workflows/test_pytest.yml
rename to .github/workflows/Future.yml
index 627e720f..39146533 100644
--- a/.github/workflows/test_pytest.yml
+++ b/.github/workflows/Future.yml
@@ -5,7 +5,9 @@ name: Future
 
 on:
   push:
-    branches: [main]
+    branches: [ main ]
+  pull_request:
+    branches: [ main ]
 
 jobs:
   build:
```

2023-01-13 14:10 UTC, teknoraver commented
This is the output of `git show`, gitpython does `git diff --numstat $commit^ $commit` which gives:
```
3       1       .github/workflows/{test_pytest.yml => Future.yml}
```
And with `--no-renames` added:
```
57      0       .github/workflows/Future.yml
0       55      .github/workflows/test_pytest.yml
```

2023-01-14 07:21 UTC, Byron approved these changes
Thanks a million, that is what I had in mind.

Thanks again for contributing!

2023-01-14 07:21 UTC, merged